org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true

plugin_group=Varyon
plugin_name=WeaponStatsViewer
plugin_version=1.8.0
plugin_description=Browse all weapons with damage stats, organized by type and rarity. Supports English and Spanish.
plugin_author=Woxtz
plugin_website=
plugin_main_entrypoint=fr.varyon.weaponstats.WeaponInfoPlugin
server_version=>=0.6.0-pre.13 <0.7.0