org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-RPG
plugin_description=RPG system: classes, jobs and interface. Knuckle assets adapted from VexhasFists (1.0.5) by VexhaThePanda.
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=fr.varyon.vrpg.VaryonRpgPlugin
server_version=>=0.6.0-pre.13 <0.7.0
sqlite_native_platform=Linux/x86_64
