org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-PlayerInteraction
plugin_version=1.2.0
plugin_description=Interact with other players: share item, F-to-interact menu (whisper, trade, party invite, profile)
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=fr.varyon.playerinteraction.PlayerInteractionPlugin
server_version=">=0.6.0-pre.13 <0.7.0"
