org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-TravelingCamera
plugin_version=1.1.0
plugin_description=Cinematic camera paths (travelings) recorded and played back per-player
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=fr.varyon.travelingcamera.VaryonTravelingCameraPlugin
server_version=>=0.6.0-pre.13 <0.7.0