org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-Trade
plugin_description=Secure player-to-player trading: item pools, optional money trading via Vault, ignore list and per-player settings.
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=fr.varyon.trade.VaryonTradePlugin
server_version=>=0.6.0-pre.13 <0.7.0
