org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-KillCommand
plugin_version=1.1.0
plugin_description=Varyon KillCommand - commandes /kill pour supprimer les mobs autour de soi ou tuer un joueur
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=com.varyon.killcommand.KillCommandPlugin
server_version=>=0.6.0-pre.13 <0.7.0