org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-Shop
plugin_description=Marchands: racheteur general, racheteurs de metier, places de marche decorations et ressources.
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=fr.varyon.shop.VaryonShopPlugin
server_version=0.5.0
