org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-EasyHunger
plugin_version=1.3.0
plugin_description=Hunger and thirst survival systems for Varyon servers
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=com.varyon.easyhunger.EasyHunger
server_version=>=0.6.0-pre.13 <0.7.0