org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

plugin_group=Varyon
plugin_name=Varyon-StackTiers
plugin_description=Gestion en jeu des paliers de stack par joueur/categorie (alternative a LuckPerms, cumulatif avec lui)
plugin_author=Varyon Team
plugin_website=

plugin_main_entrypoint=fr.varyon.stacktiers.VaryonStackTiersPlugin

server_version=>=0.6.0-pre.13 <0.7.0