org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true

plugin_group=Varyon
plugin_description=Conserve l'énergie de signature par arme lors des changements de hotbar
plugin_author=Varyon
plugin_website=
plugin_main_entrypoint=com.varyon.signaturepreservation.VaryonSignaturePreservationPlugin
server_version=2026.03.26-89796e57b
