org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-Dummy
plugin_version=1.1.0
plugin_description=Replaces the training dummy block with a custom entity that can be damaged.
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=com.varyon.dummy.DummyPlugin
server_version=>=0.6.0-pre.13 <0.7.0