org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-TpToWorld
plugin_version=1.1.0
plugin_description=Varyon TpToWorld - commande serveur /tptoworld pour teleporter un joueur vers un autre monde
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=com.varyon.tptoworld.TpToWorldPlugin
server_version=>=0.6.0-pre.13 <0.7.0