org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-MusicZones
plugin_description=3D music zones with custom OGG tracks for operators
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=fr.varyon.musiczones.VaryonMusicZonesPlugin
server_version=0.5.0
