org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

plugin_group=Varyon
plugin_name=Varyon-World-Manager
plugin_description=Per-world inventory separation and per-world game mode
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=fr.varyon.worldmanager.VaryonWorldManagerPlugin
server_version=>=0.6.0-pre.13 <0.7.0