org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-UI
plugin_version=0.1.0
plugin_description=User interface and menus for Varyon servers
plugin_author=Varyon Team
plugin_website=

plugin_main_entrypoint=com.varyon.varyonui.VaryonUIPlugin

server_version=0.5.0
