org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-Ecotale
plugin_description=Economy, physical coins and jobs (mining, mob kills, crafting) all-in-one
plugin_author=Varyon Team
plugin_website=

plugin_main_entrypoint=fr.varyon.ecotale.VaryonEcotalePlugin

server_version=0.5.0
