org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-ShareItem
plugin_version=1.0.0
plugin_description=Share your held item to chat with /share
plugin_author=Varyon Team
plugin_website=
plugin_main_entrypoint=fr.varyon.shareitem.ShareItemPlugin
server_version=0.5.0
